/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Exame;
import Classes.Solicita;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fagner
 */
public class FrameExame extends javax.swing.JDialog {

    /**
     * Creates new form FrameExame
     */
    public FrameExame(FrameAtendimento frame, boolean modal) {
        initComponents();
        habilitarPanel(false);
        this.frame = frame;
        verificaAlteracao();
    }

    private FrameAtendimento frame;
    private List<Exame> listaExames = new ArrayList<>();
    private boolean isAlteraExame = false;
    private int id;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jBTInsertFone1 = new javax.swing.JButton();
        jBTAdd1 = new javax.swing.JButton();
        jBTRemover1 = new javax.swing.JButton();
        jBTAlterar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLCentroCusto3 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLCentroCusto4 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLCentroCusto5 = new javax.swing.JLabel();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jPanel3 = new javax.swing.JPanel();
        jBTCadastrar = new javax.swing.JButton();
        jBTCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 102, 102)));

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Descrição", "Indice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabela1);

        jBTInsertFone1.setBackground(new java.awt.Color(0, 0, 0));
        jBTInsertFone1.setForeground(new java.awt.Color(255, 255, 255));
        jBTInsertFone1.setText("OK");
        jBTInsertFone1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTInsertFone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTInsertFone1ActionPerformed(evt);
            }
        });

        jBTAdd1.setBackground(new java.awt.Color(0, 0, 0));
        jBTAdd1.setForeground(new java.awt.Color(255, 255, 255));
        jBTAdd1.setText("Adicionar");
        jBTAdd1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAdd1ActionPerformed(evt);
            }
        });

        jBTRemover1.setBackground(new java.awt.Color(0, 0, 0));
        jBTRemover1.setForeground(new java.awt.Color(255, 255, 255));
        jBTRemover1.setText("Remover");
        jBTRemover1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTRemover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTRemover1ActionPerformed(evt);
            }
        });

        jBTAlterar1.setBackground(new java.awt.Color(0, 0, 0));
        jBTAlterar1.setForeground(new java.awt.Color(255, 255, 255));
        jBTAlterar1.setText("Alterar");
        jBTAlterar1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAlterar1ActionPerformed(evt);
            }
        });

        jLCentroCusto3.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto3.setText("Nome");

        jLCentroCusto4.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto4.setText("Descrição");

        jLCentroCusto5.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto5.setText("Indice de Referência");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLCentroCusto5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jLCentroCusto3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLCentroCusto4)
                                .addContainerGap())
                            .addComponent(jTextField14)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLCentroCusto4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLCentroCusto3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCentroCusto5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBTAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTRemover1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jBTAlterar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBTInsertFone1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jBTAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTRemover1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 84, Short.MAX_VALUE)
                .addComponent(jBTInsertFone1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jXTitledPanel1.setScrollableHeightHint(org.jdesktop.swingx.ScrollableSizeHint.FIT);
        jXTitledPanel1.setScrollableWidthHint(org.jdesktop.swingx.ScrollableSizeHint.HORIZONTAL_STRETCH);
        jXTitledPanel1.setTitle("Exames");
        jXTitledPanel1.setTitleFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jBTCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        jBTCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTCadastrar.setText("Gravar");
        jBTCadastrar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 10), new java.awt.Color(204, 204, 204))); // NOI18N
        jBTCadastrar.setPreferredSize(new java.awt.Dimension(71, 39));
        jBTCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCadastrarActionPerformed(evt);
            }
        });

        jBTCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jBTCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTCancelar.setText("Cancelar");
        jBTCancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 10), new java.awt.Color(204, 204, 204))); // NOI18N
        jBTCancelar.setPreferredSize(new java.awt.Dimension(71, 39));
        jBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBTCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jBTCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTInsertFone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTInsertFone1ActionPerformed
        Exame exame = new Exame(listaExames.size(), jTextField13.getText(), jTextField14.getText(), jTextField15.getText());

        if (isAlteraExame) {
            listaExames.add(id, exame);
            isAlteraExame = false;

        } else {
            listaExames.add(exame);
        }
        AtualizarListTabela(listaExames);
        habilitarPanel(false);
    }//GEN-LAST:event_jBTInsertFone1ActionPerformed

    private void jBTAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAdd1ActionPerformed
        habilitarPanel(true);
    }//GEN-LAST:event_jBTAdd1ActionPerformed

    private void jBTRemover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTRemover1ActionPerformed
        try {
            if (tabela1.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um item a ser excluido!!!", "Excluir item", 1);
            } else if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar esse lançamento?", "Excluir Lançamento", JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION) {
                int id = tabela1.getSelectedRow();
                listaExames.remove(id);
                AtualizarListTabela(listaExames);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no Excluir: " + e.getMessage(), "Exame", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBTRemover1ActionPerformed

    private void jBTAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAlterar1ActionPerformed
        try {
            if (tabela1.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um item a ser editado!!!", "Manuteção Lançamento", 1);
            } else {
                habilitarPanel(true);
                id = tabela1.getSelectedRow();
                isAlteraExame = true;
                Exame exame = listaExames.get(id);
                jTextField13.setText(exame.getNome());
                jTextField14.setText(exame.getDescricao());
                jTextField15.setText(exame.getIndexReferencia());
                listaExames.remove(id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no Excluir: " + e.getMessage(), "Fone", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBTAlterar1ActionPerformed

    private void jBTCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCadastrarActionPerformed
        frame.setListaExame(listaExames);
        dispose();
    }//GEN-LAST:event_jBTCadastrarActionPerformed

    private void jBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBTCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameExame dialog = new FrameExame(new FrameAtendimento(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAdd1;
    private javax.swing.JButton jBTAlterar1;
    private javax.swing.JButton jBTCadastrar;
    private javax.swing.JButton jBTCancelar;
    private javax.swing.JButton jBTInsertFone1;
    private javax.swing.JButton jBTRemover1;
    private javax.swing.JLabel jLCentroCusto3;
    private javax.swing.JLabel jLCentroCusto4;
    private javax.swing.JLabel jLCentroCusto5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JTable tabela1;
    // End of variables declaration//GEN-END:variables

    public void setlistaExames(List<Exame> lista) {
        this.listaExames = lista;
    }

    public List<Exame> getListaExames() {
        return listaExames;
    }

    public void habilitarPanel(boolean status) {
        jPanel4.setVisible(status);
        jBTInsertFone1.setVisible(status);
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
    }

    public void AtualizarListTabela(List<Exame> lista) {
        try {

            tabela1.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabela1.getColumnModel().getColumn(1).setPreferredWidth(50);
            tabela1.getColumnModel().getColumn(2).setPreferredWidth(50);
            setlistaExames(lista);
            DefaultTableModel modelo = (DefaultTableModel) tabela1.getModel();
            modelo.setNumRows(0);
            for (Exame item : lista) {
                modelo.addRow(new Object[]{
                    item.getNome(), item.getDescricao(), item.getIndexReferencia()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao  AtualizarListTabela!!!");
        }
    }

    private void verificaAlteracao() {
        if (frame.isIsAlteraSolicitacao()) {
            setlistaExames(frame.getListaExame());
            AtualizarListTabela(listaExames);
        }
    }

}
