/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Anamnese;
import Classes.Atende;
import Classes.Atendimento;
import Classes.Exame;
import Classes.Medico;
import Classes.Paciente;
import Classes.Prontuario;
import Classes.Solicita;
import Manager.AtendeManager;
import Manager.AtendimentoManager;
import Manager.MedicoManager;
import Manager.PacienteManager;
import Manager.ProntuarioManager;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fagner
 */
public class FrameAtendimento extends javax.swing.JFrame {

    /**
     * Creates new form FrameAtendimento
     */
    public FrameAtendimento() {
        initComponents();
        InicializaComponente();

    }

    private PacienteManager pacienteManager = new PacienteManager();
    private MedicoManager medicoManager = new MedicoManager();
    private List<Anamnese> listaAnmAnamneses = new ArrayList<>();
    private List<Solicita> listaSolicitas = new ArrayList<>();
    private AtendeManager atendeManager = new AtendeManager();
    private AtendimentoManager antendiAtendimentoManager = new AtendimentoManager();
    private ProntuarioManager prontuarioManager = new ProntuarioManager();
    private List<Medico> listaMedico;
    private List<Paciente> listaPaciente;
    private int id;
    private int gambi = 0;
    private boolean isAlteraAnamnese = false;
    private boolean isAlteraSolicitacao = false;
    private Solicita auxSolicita;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jXDData = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jBTInsertFone = new javax.swing.JButton();
        jBTAdd = new javax.swing.JButton();
        jBTRemover = new javax.swing.JButton();
        jBTAlterar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLCentroCusto = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLCentroCusto2 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        jXDData1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jBTInsertFone1 = new javax.swing.JButton();
        jBTAdd1 = new javax.swing.JButton();
        jBTRemover1 = new javax.swing.JButton();
        jBTAlterar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLCentroCusto1 = new javax.swing.JLabel();
        jLCentroCusto3 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jXDData2 = new org.jdesktop.swingx.JXDatePicker();
        jTextField14 = new javax.swing.JTextField();
        jLCentroCusto4 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLCentroCusto5 = new javax.swing.JLabel();
        jBTInsertFone2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jBTCadastrar = new javax.swing.JButton();
        jBTCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(this.MAXIMIZED_BOTH);

        jXTitledPanel1.setScrollableHeightHint(org.jdesktop.swingx.ScrollableSizeHint.FIT);
        jXTitledPanel1.setScrollableWidthHint(org.jdesktop.swingx.ScrollableSizeHint.HORIZONTAL_STRETCH);
        jXTitledPanel1.setTitle("Atendimento");
        jXTitledPanel1.setTitleFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Paciente");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Prontuario");

        jXDData.setBorder(dropShadowBorder1
        );
        jXDData.setForeground(new java.awt.Color(255, 0, 0));
        jXDData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Data");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 102, 102)));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pergunta", "Resposta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela);

        jBTInsertFone.setBackground(new java.awt.Color(0, 0, 0));
        jBTInsertFone.setForeground(new java.awt.Color(255, 255, 255));
        jBTInsertFone.setText("OK");
        jBTInsertFone.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTInsertFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTInsertFoneActionPerformed(evt);
            }
        });

        jBTAdd.setBackground(new java.awt.Color(0, 0, 0));
        jBTAdd.setForeground(new java.awt.Color(255, 255, 255));
        jBTAdd.setText("Adicionar");
        jBTAdd.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAddActionPerformed(evt);
            }
        });

        jBTRemover.setBackground(new java.awt.Color(0, 0, 0));
        jBTRemover.setForeground(new java.awt.Color(255, 255, 255));
        jBTRemover.setText("Remover");
        jBTRemover.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTRemoverActionPerformed(evt);
            }
        });

        jBTAlterar.setBackground(new java.awt.Color(0, 0, 0));
        jBTAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBTAlterar.setText("Alterar");
        jBTAlterar.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAlterarActionPerformed(evt);
            }
        });

        jLCentroCusto.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto.setText("Pergunta");

        jLCentroCusto2.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto2.setText("Resposta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLCentroCusto2)
                        .addGap(299, 299, 299)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLCentroCusto)
                    .addContainerGap(618, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLCentroCusto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLCentroCusto)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBTAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTRemover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jBTAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBTInsertFone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBTAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBTInsertFone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jXDData1.setBorder(dropShadowBorder1
        );
        jXDData1.setForeground(new java.awt.Color(255, 0, 0));
        jXDData1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Data Inicio Prontuario");

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 102, 102)));

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Laboratório", "Observação", "Resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabela1);

        jBTInsertFone1.setBackground(new java.awt.Color(0, 0, 0));
        jBTInsertFone1.setForeground(new java.awt.Color(255, 255, 255));
        jBTInsertFone1.setText("OK");
        jBTInsertFone1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTInsertFone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTInsertFone1ActionPerformed(evt);
            }
        });

        jBTAdd1.setBackground(new java.awt.Color(0, 0, 0));
        jBTAdd1.setForeground(new java.awt.Color(255, 255, 255));
        jBTAdd1.setText("Adicionar");
        jBTAdd1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAdd1ActionPerformed(evt);
            }
        });

        jBTRemover1.setBackground(new java.awt.Color(0, 0, 0));
        jBTRemover1.setForeground(new java.awt.Color(255, 255, 255));
        jBTRemover1.setText("Remover");
        jBTRemover1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTRemover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTRemover1ActionPerformed(evt);
            }
        });

        jBTAlterar1.setBackground(new java.awt.Color(0, 0, 0));
        jBTAlterar1.setForeground(new java.awt.Color(255, 255, 255));
        jBTAlterar1.setText("Alterar");
        jBTAlterar1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAlterar1ActionPerformed(evt);
            }
        });

        jLCentroCusto1.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto1.setText("Data");

        jLCentroCusto3.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto3.setText("Laboratório");

        jXDData2.setBorder(dropShadowBorder1
        );
        jXDData2.setForeground(new java.awt.Color(255, 0, 0));
        jXDData2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLCentroCusto4.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto4.setText("Oberservação");

        jLCentroCusto5.setBackground(new java.awt.Color(255, 255, 255));
        jLCentroCusto5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCentroCusto5.setText("Resultado");

        jBTInsertFone2.setBackground(new java.awt.Color(0, 0, 0));
        jBTInsertFone2.setForeground(new java.awt.Color(255, 255, 255));
        jBTInsertFone2.setText("Adicionar Exame");
        jBTInsertFone2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), null));
        jBTInsertFone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTInsertFone2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jXDData2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLCentroCusto1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLCentroCusto3)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLCentroCusto5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField14)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLCentroCusto4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBTInsertFone2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLCentroCusto4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCentroCusto3)
                            .addComponent(jLCentroCusto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLCentroCusto5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBTInsertFone2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBTAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTRemover1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jBTAlterar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBTInsertFone1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jBTAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTRemover1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jBTInsertFone1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Médico");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Solicitação");

        jBTCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        jBTCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTCadastrar.setText("Gravar");
        jBTCadastrar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 10), new java.awt.Color(204, 204, 204))); // NOI18N
        jBTCadastrar.setPreferredSize(new java.awt.Dimension(71, 39));
        jBTCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCadastrarActionPerformed(evt);
            }
        });

        jBTCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jBTCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBTCancelar.setText("Cancelar");
        jBTCancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 10), new java.awt.Color(204, 204, 204))); // NOI18N
        jBTCancelar.setPreferredSize(new java.awt.Dimension(71, 39));
        jBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBTCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(521, 521, 521)
                .addComponent(jBTCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(342, 342, 342)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jXDData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jXDData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTInsertFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTInsertFoneActionPerformed
        GravarAnamnese();
    }//GEN-LAST:event_jBTInsertFoneActionPerformed

    private void jBTAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAddActionPerformed
        InserirAnamnese();
    }//GEN-LAST:event_jBTAddActionPerformed

    private void jBTRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTRemoverActionPerformed
        RemoverAnamnese();
    }//GEN-LAST:event_jBTRemoverActionPerformed

    private void jBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAlterarActionPerformed
        AlterarAnamnese();
    }//GEN-LAST:event_jBTAlterarActionPerformed

    private void jBTAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAlterar1ActionPerformed
        Alterarsolicitacao();
    }//GEN-LAST:event_jBTAlterar1ActionPerformed

    private void jBTRemover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTRemover1ActionPerformed
        RemoverSolitacao();
    }//GEN-LAST:event_jBTRemover1ActionPerformed

    private void jBTAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAdd1ActionPerformed
        InsereSolicitacao();
    }//GEN-LAST:event_jBTAdd1ActionPerformed

    private void jBTInsertFone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTInsertFone1ActionPerformed
        GravarSolicitacao();
    }//GEN-LAST:event_jBTInsertFone1ActionPerformed

    private void jBTInsertFone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTInsertFone2ActionPerformed
        if (gambi == 0) {
            FrameExame frame = new FrameExame(this, true);
            frame.setVisible(true);
            gambi++;
        } else {
            isAlteraSolicitacao = true;
            FrameExame frame = new FrameExame(this, true);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_jBTInsertFone2ActionPerformed

    private void jBTCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCadastrarActionPerformed
        GravarAtendimento();
        dispose();
    }//GEN-LAST:event_jBTCadastrarActionPerformed

    private void jBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCancelarActionPerformed
        MenuPrincipal frame = new MenuPrincipal(0);
        frame.show(true); 
        dispose();
    }//GEN-LAST:event_jBTCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAdd;
    private javax.swing.JButton jBTAdd1;
    private javax.swing.JButton jBTAlterar;
    private javax.swing.JButton jBTAlterar1;
    private javax.swing.JButton jBTCadastrar;
    private javax.swing.JButton jBTCancelar;
    private javax.swing.JButton jBTInsertFone;
    private javax.swing.JButton jBTInsertFone1;
    private javax.swing.JButton jBTInsertFone2;
    private javax.swing.JButton jBTRemover;
    private javax.swing.JButton jBTRemover1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLCentroCusto;
    private javax.swing.JLabel jLCentroCusto1;
    private javax.swing.JLabel jLCentroCusto2;
    private javax.swing.JLabel jLCentroCusto3;
    private javax.swing.JLabel jLCentroCusto4;
    private javax.swing.JLabel jLCentroCusto5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private org.jdesktop.swingx.JXDatePicker jXDData;
    private org.jdesktop.swingx.JXDatePicker jXDData1;
    private org.jdesktop.swingx.JXDatePicker jXDData2;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabela1;
    // End of variables declaration//GEN-END:variables

    private void InicializaComponente() {
        listaMedico = medicoManager.getALL();
        listaPaciente = pacienteManager.getALL();
        jXDData.setDate(new Date());
        jXDData1.setDate(new Date());
        HabilitarPanelSolicita(false);
        HabilitarPanelProntuario(false);
        setListaMedico(jComboBox2, listaMedico);
        setListaPaciente(jComboBox1, listaPaciente);

    }

    public void setListaMedico(JComboBox combo, List<Medico> medico) {
        org.jdesktop.beansbinding.BindingGroup bindingGroup;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, medico, combo, "");
        bindingGroup.addBinding(jComboBoxBinding);
        bindingGroup.bind();
    }

    public void setListaPaciente(JComboBox combo, List<Paciente> paciente) {
        org.jdesktop.beansbinding.BindingGroup bindingGroup;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, paciente, combo, "");
        bindingGroup.addBinding(jComboBoxBinding);
        bindingGroup.bind();
    }

    public List<Anamnese> getListaAnmAnamneses() {
        return listaAnmAnamneses;
    }

    public void setListaAnmAnamneses(List<Anamnese> listaAnmAnamneses) {
        this.listaAnmAnamneses = listaAnmAnamneses;
    }

    private void GravarAtendimento() {
        //Estou com duvida o que vou gravar
        Atende atende = new Atende();
        atende.setData(jXDData.getDate());
     //atendeManager.create(atende);
        
        Paciente paciente = listaPaciente.get(jComboBox1.getSelectedIndex());    //Paciente selecionado
        Medico medico = listaMedico.get(jComboBox2.getSelectedIndex());          //Medico selectionado
        
        Atendimento atendimento = new Atendimento();
        atendimento.setListaSolicitacao(listaSolicitas);
     //antendiAtendimentoManager.create(atendimento);
        
        Prontuario prontuario = new Prontuario();
        prontuario.setDataInicio(jXDData1.getDate());
        prontuario.setListaAnamnese(listaAnmAnamneses);
        prontuario.setListaSolicita(listaSolicitas);
        prontuarioManager.create(prontuario);
        
       

    }

    private void InsereSolicitacao() {
        HabilitarPanelSolicita(true);
        auxSolicita = new Solicita();

    }

    public List<Solicita> getListaSolicitas() {
        return listaSolicitas;
    }

    public void setListaSolicitas(List<Solicita> listaSolicitas) {
        this.listaSolicitas = listaSolicitas;
    }

    public void setListaExame(List<Exame> lista) {
        this.auxSolicita.setListaExame(lista);
    }

    public List<Exame> getListaExame() {
        return this.auxSolicita.getListaExame();
    }

    private void HabilitarPanelSolicita(boolean status) {

        jPanel4.setVisible(status);
        jBTInsertFone1.setVisible(status);
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");

    }

    private void HabilitarPanelProntuario(boolean status) {
        jPanel3.setVisible(status);
        jBTInsertFone.setVisible(status);
        jTextField10.setText("");
        jTextField11.setText("");
    }

    public void AtualizarListTabelaProntuario(List<Anamnese> lista) {
        try {

            tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(50);
            setListaAnmAnamneses(lista);
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            modelo.setNumRows(0);
            for (Anamnese item : lista) {
                modelo.addRow(new Object[]{
                    item.getPergunta(), item.getResposta()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao  AtualizarListTabelaProntuario!!!");
        }
    }

    public void AtualizarListTabelaSolicitacao(List<Solicita> lista) {
        try {

            tabela1.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabela1.getColumnModel().getColumn(1).setPreferredWidth(50);
            tabela1.getColumnModel().getColumn(2).setPreferredWidth(50);
            tabela1.getColumnModel().getColumn(3).setPreferredWidth(50);
            setListaSolicitas(lista);
            DefaultTableModel modelo = (DefaultTableModel) tabela1.getModel();
            modelo.setNumRows(0);
            for (Solicita item : lista) {
                modelo.addRow(new Object[]{
                    item.getData(), item.getLaboratorio(), item.getObservacao(), item.getResultado()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao  AtualizarListTabelaSolicitacao!!!");
        }
    }

    private void InserirAnamnese() {
        HabilitarPanelProntuario(true);

    }

    private void GravarAnamnese() {
        Anamnese anamnese = new Anamnese(jTextField10.getText(), jTextField11.getText());
        if (isAlteraAnamnese) {
            listaAnmAnamneses.add(id, anamnese);
            isAlteraAnamnese = false;
        } else {
            listaAnmAnamneses.add(anamnese);
        }
        HabilitarPanelProntuario(false);
        AtualizarListTabelaProntuario(listaAnmAnamneses);
    }

    private void GravarSolicitacao() {
        Solicita solicita = new Solicita();
        solicita.setListaExame(auxSolicita.getListaExame());
        solicita.setData(jXDData2.getDate());
        solicita.setLaboratorio(jTextField13.getText());
        solicita.setObservacao(jTextField14.getText());
        solicita.setResultado(jTextField15.getText());
        if (isAlteraSolicitacao) {
            listaSolicitas.add(id, solicita);
            isAlteraSolicitacao = false;

        } else {
            listaSolicitas.add(solicita);
        }
        AtualizarListTabelaSolicitacao(listaSolicitas);
        HabilitarPanelSolicita(false);

    }

    private void RemoverAnamnese() {
        try {
            if (tabela.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um item a ser excluido!!!", "Excluir item", 1);
            } else if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar esse lançamento?", "Excluir Lançamento", JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION) {
                int id = tabela.getSelectedRow();
                listaAnmAnamneses.remove(id);
                AtualizarListTabelaProntuario(listaAnmAnamneses);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no Excluir: " + e.getMessage(), "Fone", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void RemoverSolitacao() {
        try {
            if (tabela1.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um item a ser excluido!!!", "Excluir item", 1);
            } else if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar esse lançamento?", "Excluir Lançamento", JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION) {
                int id = tabela1.getSelectedRow();
                listaSolicitas.remove(id);
                AtualizarListTabelaSolicitacao(listaSolicitas);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no Excluir: " + e.getMessage(), "Fone", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void AlterarAnamnese() {
        try {
            if (tabela.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um item a ser editado!!!", "Manuteção Lançamento", 1);
            } else {
                HabilitarPanelProntuario(true);
                id = tabela.getSelectedRow();
                isAlteraAnamnese = true;
                Anamnese anamnese = listaAnmAnamneses.get(id);
                jTextField10.setText(anamnese.getPergunta());
                jTextField11.setText(anamnese.getResposta());
                listaAnmAnamneses.remove(id);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no Excluir: " + e.getMessage(), "Fone", JOptionPane.ERROR_MESSAGE);
        }

    }

    public boolean isIsAlteraSolicitacao() {
        return this.isAlteraSolicitacao;
    }

    private void Alterarsolicitacao() {
        try {
            if (tabela1.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione um item a ser editado!!!", "Manuteção Lançamento", 1);
            } else {
                HabilitarPanelSolicita(true);
                id = tabela1.getSelectedRow();
                isAlteraSolicitacao = true;
                Solicita solicita = listaSolicitas.get(id);
                auxSolicita = solicita;
                jXDData2.setDate(solicita.getData());
                jTextField13.setText(solicita.getLaboratorio());
                jTextField14.setText(solicita.getObservacao());
                jTextField15.setText(solicita.getResultado());
                listaSolicitas.remove(id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro no Excluir: " + e.getMessage(), "Fone", JOptionPane.ERROR_MESSAGE);
        }
    }

}
